// Builds a Google Fonts CSS2 stylesheet URL for the given font family names (as generated by
// the setup-agent's `setTheme` tool). Names are trimmed and space-joined with "+" per the
// Google Fonts URL convention; duplicate family names are only requested once.
export function googleFontsHref(...families: string[]): string {
  const unique = Array.from(new Set(families.filter(Boolean).map((f) => f.trim())));
  const query = unique.map((f) => `family=${f.replace(/\s+/g, '+')}`).join('&');
  return `https://fonts.googleapis.com/css2?${query}&display=swap`;
}
